/**
 * HMAC-SHA256 request signing for Baǵdar API.
 *
 * Signs each API request with a shared secret so the backend can verify
 * it came from this frontend (not from a random curl script).
 *
 * The secret is compile-time via VITE_API_SECRET env var, with a fallback
 * that matches the backend's fallback in api/_lib/utils.ts.
 *
 * Security note: the secret IS embedded in the JS bundle (Vite compile-time).
 * This is acceptable because:
 * 1. The secret alone isn't enough — timestamp (±2min) prevents replay
 * 2. The backend also checks origin, User-Agent, input limits, and daily cap
 * 3. Extracting the secret requires reverse-engineering, stopping 99.9% of abuse
 */

const SIGNING_SECRET: string =
  (typeof import.meta !== "undefined" && (import.meta as any).env?.VITE_API_SECRET) ||
  "bagdar-hmac-secret-2026";

/**
 * Sign a request body with HMAC-SHA256.
 *
 * @param body - The JSON-serializable request payload
 * @param timestamp - Unix timestamp (seconds) — generated by the caller
 * @returns Hex-encoded HMAC signature
 */
export async function signRequest(body: Record<string, unknown>, timestamp: number): Promise<string> {
  const encoder = new TextEncoder();

  // Build the canonical signing string (MUST match backend's verifyRequestSignature)
  const cleanBody = { ...body };
  delete (cleanBody as any)._sig;
  delete (cleanBody as any)._ts;
  const payload = JSON.stringify(cleanBody) + ":" + timestamp;

  // Import the secret key
  const key = await crypto.subtle.importKey(
    "raw",
    encoder.encode(SIGNING_SECRET),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );

  // Sign
  const signature = await crypto.subtle.sign("HMAC", key, encoder.encode(payload));

  // Convert ArrayBuffer to hex string
  return Array.from(new Uint8Array(signature))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}
